# https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs

name: Release

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment'
        required: true

# env:
#   AWS_EB_S3_BUCKET: elasticbeanstalk-ap-northeast-2-${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        run: echo "${{ github.event.inputs.comment }}"
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps
      - run: npm run build

      - name: Release
        run: npx semantic-release

      - name: Version Check
        if: ${{ !env.RELEASE_VERSION }}
        run: exit 1

      - name: Release Version
        run: |
          echo "$RELEASE_VERSION"
          echo "DEPLOY_VERSION=gql-v$RELEASE_VERSION" >> $GITHUB_ENV
      - name: Deploy Version
        run: echo "$DEPLOY_VERSION"

      - name: Fetch Release Tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false

      - name: Create Source Bundle
        run: |
          git archive --format=zip v$RELEASE_VERSION -o $DEPLOY_VERSION.zip
          zip -urq $DEPLOY_VERSION.zip dist
